[theme]
primaryColor = "#00c853"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#2e2e2e"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[client]
showSidebarNavigation = true

[ui]
initialSidebarState = "auto"
hideSidebarNav = false
