[theme]
base="dark"
primaryColor="#00c853"              # Verde brillante (acentos y botones)
backgroundColor="#121212"           # Fondo principal oscuro
secondaryBackgroundColor="#1e1e1e"  # Fondo del menú lateral (sidebar)
textColor="#ffffff"                 # Texto blanco
font="sans serif"

